### ISSUE TITLE
Error: Invalid username or password

### ISSUE THREAD

**Issue by saydulk** [QuantumObject/docker-koha#10]
I have install koha https://hub.docker.com/r/quantumobject/docker-koha/

After run i use username: koha_kohadev and pass: password to login koha but fail

![Screenshot from 2019-04-18 03-12-23](https://user-images.githubusercontent.com/1058663/56321239-ef9c7c00-6187-11e9-9402-b81b249b6fc2.png)

**Comment by angelrr7702** [comment]
that is for the web installer where the login suppose to be by 

koha_library

and password will be the one you get by running 

docker logs container_id

sincerely
Angel Rodriguez
