### ISSUE TITLE
setgid(1000): operation not permitted

### ISSUE THREAD

**Issue by useltmann** [QuantumObject/docker-koha#3]
i always get *500 Internal Server Error* when accessing port 80 or 8080. a look at apache2's error.log shows

    [mpm_itk:warn] [pid 2312] (itkmpm: pid=2312 uid=33, gid=33) itk_post_perdir_config(): setgid(1000): Operation not permitted

although they seem to be warnings, not errors.

**Comment by angelrr7702** [comment]
need to restart apache2 manual by /etc/init.d/apache2 restart command by accessing container with 

docker exec -it container_id /bin/bash

after that it will work ... 
 
the problem with mpm_itk and apache2 and this version of ubuntu . at the moment no idea how to fix that problem with     koha , trying to restart apache2 from script don't work ... 

if you find a solution let me know .

**Comment by angelrr7702** [comment]
I update to version 3.21 from 3.19  but still the same problem ....

This is a know problem for installing koha on ubuntu ... if you check koha documentation show how to fix it manually but that only work if you are installing it by command line , command by command .

at the moment ,need to restart apache by command line when show this "500 Internal Server Error", if you stop and start the container (like when rebooting the server) need to do it too .. 

the original documentation for koha is to be installed on debian and they said that normal debian is the recommended linux distribution .. 

This procedure already been include in container REAME.md file.

**Comment by useltmann** [comment]
i tried to install on debian jessie (on docker) and i got the same error. it seems to be a problem in conjunction with mpm-itk and docker here.
right now i try to install from koha sources, since they dont require mpm-itk. sad that the packages do though.

**Comment by useltmann** [comment]
seems like its an issue with newish mpm-itk/apache2? using wheezy instead of jessie works flawlessly.
anyways the issue is neither the image nor its docker. closing this

**Comment by angelrr7702** [comment]
Yes, thanks for trying .. I will keep at the moment on this way .. hope that they fix it for future version .  I can't have different base-image for my containers or it will make it more difficult to maintain them.  normal I will try to keep the last stable Ubuntu base-image for my container but that maybe change too because of systemd change at Ubuntu new release.

**Comment by lordspace** [comment]
hi all,

I had the same issue. 
This ticket [https://github.com/moby/moby/issues/9734] shows a solution by adding to these lines to the run command.
`--cap-add=SYS_NICE --cap-add=DAC_READ_SEARCH`

**Comment by angelrr7702** [comment]
Thanks
